# KhushiDL - Heart Disease (EDA)

In [73]:
# importing the necessary modules
import pandas as pd

### Reading the Data

In [74]:
# Viewing adjustments
pd.set_option('display.max_rows', None)  # Shows all rows
pd.set_option('display.max_columns', None)  # Shows all columns
pd.set_option('display.width', 1000)  # Prevents wrapping to new lines

In [75]:
# loading the dataset
swiss_data = pd.read_csv('data/processed.switzerland.data', header=None)
cleve_data = pd.read_csv('data/processed.cleveland.data', header=None)
hungarian_data = pd.read_csv('data/processed.hungarian.data')
va_data = pd.read_csv('data/processed.va.data')

## Swiss Data 🇨🇭

In [76]:
# preliminary report of data
swiss_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 123 entries, 0 to 122
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       123 non-null    int64
 1   1       123 non-null    int64
 2   2       123 non-null    int64
 3   3       123 non-null    str
 4   4       123 non-null    int64
 5   5       123 non-null    str
 6   6       123 non-null    str
 7   7       123 non-null    str
 8   8       123 non-null    str
 9   9       123 non-null    str
 10  10      123 non-null    str
 11  11      123 non-null    str
 12  12      123 non-null    str
 13  13      123 non-null    int64
dtypes: int64(5), str(9)
memory usage: 13.6 KB

In [77]:
swiss_data.head()

   0   1   2    3   4  5  6    7  8    9  10 11 12  13
0  32   1   1   95   0  ?  0  127  0   .7  1  ?  ?   1
1  34   1   4  115   0  ?  ?  154  0   .2  1  ?  ?   1
2  35   1   4    ?   0  ?  0  130  1    ?  ?  ?  7   3
3  36   1   4  110   0  ?  0  125  1    1  2  ?  6   1
4  38   0   4  105   0  ?  0  166  0  2.8  1  ?  ?   2

In [78]:
swiss_data.describe(include='all')
# use include='all' to describe all the columns
# NaN means Not A Value
# NaN + anything(integer, float like 8 or 5.0) = NaN

                0           1           2    3      4    5    6    7    8    9    10   11   12          13
count   123.000000  123.000000  123.000000  123  123.0  123  123  123  123  123  123  123  123  123.000000
unique         NaN         NaN         NaN   21    NaN    3    4   68    3   36    4    3    4         NaN
top            NaN         NaN         NaN  115    NaN    ?    0  120    0    0    2    ?    ?         NaN
freq           NaN         NaN         NaN   14    NaN   75   85    9   68   42   61  118   52         NaN
mean     55.317073    0.918699    3.699187  NaN    0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    1.804878
std       9.032108    0.274414    0.688726  NaN    0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    1.013503
min      32.000000    0.000000    1.000000  NaN    0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    0.000000
25%      51.000000    1.000000    4.000000  NaN    0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    1.000000
50%      56.000000    1.000000    4.000000  NaN    0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    2.000000
75%      61.500000    1.000000    4.000000  NaN    0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    3.000000
max      74.000000    1.000000    4.000000  NaN    0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    4.000000

In [79]:
swiss_data = swiss_data.replace('?', pd.NA) # replacing the ? with 0s
# since the 3rd index column is actually a string, that's why the values are NaN.
# due to jupyter notebook's internal memory, sometimes previous states, given to replace are logged permanently.
# reruning all the cells once again would wave it off.

In [80]:
# changing the datatype 
swiss_data = swiss_data.astype(float)

In [81]:
swiss_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 123 entries, 0 to 122
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       123 non-null    float64
 1   1       123 non-null    float64
 2   2       123 non-null    float64
 3   3       121 non-null    float64
 4   4       123 non-null    float64
 5   5       48 non-null     float64
 6   6       122 non-null    float64
 7   7       122 non-null    float64
 8   8       122 non-null    float64
 9   9       117 non-null    float64
 10  10      106 non-null    float64
 11  11      5 non-null      float64
 12  12      71 non-null     float64
 13  13      123 non-null    float64
dtypes: float64(14)
memory usage: 13.6 KB

In [82]:
swiss_data.describe(include='all')

               0           1           2           3      4          5           6           7           8           9           10        11         12          13
count  123.000000  123.000000  123.000000  121.000000  123.0  48.000000  122.000000  122.000000  122.000000  117.000000  106.000000  5.000000  71.000000  123.000000
mean    55.317073    0.918699    3.699187  130.206612    0.0   0.104167    0.360656  121.557377    0.442623    0.653846    1.801887  1.600000   5.788732    1.804878
std      9.032108    0.274414    0.688726   22.559151    0.0   0.308709    0.590077   25.977438    0.498745    1.056061    0.623658  0.547723   1.731354    1.013503
min     32.000000    0.000000    1.000000   80.000000    0.0   0.000000    0.000000   60.000000    0.000000   -2.600000    1.000000  1.000000   3.000000    0.000000
25%     51.000000    1.000000    4.000000  115.000000    0.0   0.000000    0.000000  104.250000    0.000000    0.000000    1.000000  1.000000   3.000000    1.000000
50%     56.000000    1.000000    4.000000  125.000000    0.0   0.000000    0.000000  121.000000    0.000000    0.300000    2.000000  2.000000   7.000000    2.000000
75%     61.500000    1.000000    4.000000  145.000000    0.0   0.000000    1.000000  140.000000    1.000000    1.500000    2.000000  2.000000   7.000000    3.000000
max     74.000000    1.000000    4.000000  200.000000    0.0   1.000000    2.000000  182.000000    1.000000    3.700000    3.000000  2.000000   7.000000    4.000000

### Swiss 🇨🇭 Data - Final Analysis
---
### Points
- We will drop the 4<sup>th</sup> index column, as all the values are Zeroes
- We will drop the 11<sup>th</sup> index column, as very few values are present. Imputation not possible
- We will not drop the 5<sup>th</sup> index of Fasting Blood sugar, we will assign the mean value to it. (Median value not permissible as they are binary)
- Rest all the data will be polished

In [83]:
# Plotting Swiss Graphs
swiss_data.T.index

Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13], dtype='int64')

In [84]:
swiss_data.T.iloc[5].var()

np.float64(0.09530141843971632)

### Purging Swiss Data

In [85]:
swiss_data = swiss_data.drop([4, 11], axis='columns')

In [86]:
swiss_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 123 entries, 0 to 122
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       123 non-null    float64
 1   1       123 non-null    float64
 2   2       123 non-null    float64
 3   3       121 non-null    float64
 4   5       48 non-null     float64
 5   6       122 non-null    float64
 6   7       122 non-null    float64
 7   8       122 non-null    float64
 8   9       117 non-null    float64
 9   10      106 non-null    float64
 10  12      71 non-null     float64
 11  13      123 non-null    float64
dtypes: float64(12)
memory usage: 11.7 KB

In [87]:
swiss_data.describe(include='all')

               0           1           2           3          5           6           7           8           9           10         12          13
count  123.000000  123.000000  123.000000  121.000000  48.000000  122.000000  122.000000  122.000000  117.000000  106.000000  71.000000  123.000000
mean    55.317073    0.918699    3.699187  130.206612   0.104167    0.360656  121.557377    0.442623    0.653846    1.801887   5.788732    1.804878
std      9.032108    0.274414    0.688726   22.559151   0.308709    0.590077   25.977438    0.498745    1.056061    0.623658   1.731354    1.013503
min     32.000000    0.000000    1.000000   80.000000   0.000000    0.000000   60.000000    0.000000   -2.600000    1.000000   3.000000    0.000000
25%     51.000000    1.000000    4.000000  115.000000   0.000000    0.000000  104.250000    0.000000    0.000000    1.000000   3.000000    1.000000
50%     56.000000    1.000000    4.000000  125.000000   0.000000    0.000000  121.000000    0.000000    0.300000    2.000000   7.000000    2.000000
75%     61.500000    1.000000    4.000000  145.000000   0.000000    1.000000  140.000000    1.000000    1.500000    2.000000   7.000000    3.000000
max     74.000000    1.000000    4.000000  200.000000   1.000000    2.000000  182.000000    1.000000    3.700000    3.000000   7.000000    4.000000

## Cleveland Data

In [88]:
cleve_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       303 non-null    float64
 1   1       303 non-null    float64
 2   2       303 non-null    float64
 3   3       303 non-null    float64
 4   4       303 non-null    float64
 5   5       303 non-null    float64
 6   6       303 non-null    float64
 7   7       303 non-null    float64
 8   8       303 non-null    float64
 9   9       303 non-null    float64
 10  10      303 non-null    float64
 11  11      303 non-null    str
 12  12      303 non-null    str
 13  13      303 non-null    int64
dtypes: float64(11), int64(1), str(2)
memory usage: 33.3 KB

In [89]:
cleve_data = cleve_data.replace('?', pd.NA) # for better analysis

In [90]:
cleve_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       303 non-null    float64
 1   1       303 non-null    float64
 2   2       303 non-null    float64
 3   3       303 non-null    float64
 4   4       303 non-null    float64
 5   5       303 non-null    float64
 6   6       303 non-null    float64
 7   7       303 non-null    float64
 8   8       303 non-null    float64
 9   9       303 non-null    float64
 10  10      303 non-null    float64
 11  11      299 non-null    str
 12  12      301 non-null    str
 13  13      303 non-null    int64
dtypes: float64(11), int64(1), str(2)
memory usage: 33.3 KB

In [91]:
cleve_data = cleve_data.astype(float) #change type

In [92]:
cleve_data.describe(include='all')

               0           1           2           3           4           5           6           7           8           9           10          11          12          13
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000  299.000000  301.000000  303.000000
mean    54.438944    0.679868    3.158416  131.689769  246.693069    0.148515    0.990099  149.607261    0.326733    1.039604    1.600660    0.672241    4.734219    0.937294
std      9.038662    0.467299    0.960126   17.599748   51.776918    0.356198    0.994971   22.875003    0.469794    1.161075    0.616226    0.937438    1.939706    1.228536
min     29.000000    0.000000    1.000000   94.000000  126.000000    0.000000    0.000000   71.000000    0.000000    0.000000    1.000000    0.000000    3.000000    0.000000
25%     48.000000    0.000000    3.000000  120.000000  211.000000    0.000000    0.000000  133.500000    0.000000    0.000000    1.000000    0.000000    3.000000    0.000000
50%     56.000000    1.000000    3.000000  130.000000  241.000000    0.000000    1.000000  153.000000    0.000000    0.800000    2.000000    0.000000    3.000000    0.000000
75%     61.000000    1.000000    4.000000  140.000000  275.000000    0.000000    2.000000  166.000000    1.000000    1.600000    2.000000    1.000000    7.000000    2.000000
max     77.000000    1.000000    4.000000  200.000000  564.000000    1.000000    2.000000  202.000000    1.000000    6.200000    3.000000    3.000000    7.000000    4.000000

In [93]:
cleve_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       303 non-null    float64
 1   1       303 non-null    float64
 2   2       303 non-null    float64
 3   3       303 non-null    float64
 4   4       303 non-null    float64
 5   5       303 non-null    float64
 6   6       303 non-null    float64
 7   7       303 non-null    float64
 8   8       303 non-null    float64
 9   9       303 non-null    float64
 10  10      303 non-null    float64
 11  11      299 non-null    float64
 12  12      301 non-null    float64
 13  13      303 non-null    float64
dtypes: float64(14)
memory usage: 33.3 KB

## Cleveland data analysis
---
### Points
- Cleveland data is Healthy data
- Very few values are missing, hence we will use it entirely and Impute necessary data in the actual model itself