# KhushiDL - Heart Disease (EDA)

In [52]:
# importing the necessary modules
import pandas as pd

### Reading the Data

In [53]:
# Viewing adjustments
pd.set_option('display.max_rows', None)  # Shows all rows
pd.set_option('display.max_columns', None)  # Shows all columns
pd.set_option('display.width', 1000)  # Prevents wrapping to new lines

In [54]:
# loading the dataset
swiss_data = pd.read_csv('data/processed.switzerland.data', header=None)
cleve_data = pd.read_csv('data/processed.cleveland.data')
hungarian_data = pd.read_csv('data/processed.hungarian.data')
va_data = pd.read_csv('data/processed.va.data')

### Swiss Data 🇨🇭

In [55]:
# preliminary report of data
swiss_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 123 entries, 0 to 122
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       123 non-null    int64
 1   1       123 non-null    int64
 2   2       123 non-null    int64
 3   3       123 non-null    str
 4   4       123 non-null    int64
 5   5       123 non-null    str
 6   6       123 non-null    str
 7   7       123 non-null    str
 8   8       123 non-null    str
 9   9       123 non-null    str
 10  10      123 non-null    str
 11  11      123 non-null    str
 12  12      123 non-null    str
 13  13      123 non-null    int64
dtypes: int64(5), str(9)
memory usage: 13.6 KB

In [56]:
swiss_data.head()

   0   1   2    3   4  5  6    7  8    9  10 11 12  13
0  32   1   1   95   0  ?  0  127  0   .7  1  ?  ?   1
1  34   1   4  115   0  ?  ?  154  0   .2  1  ?  ?   1
2  35   1   4    ?   0  ?  0  130  1    ?  ?  ?  7   3
3  36   1   4  110   0  ?  0  125  1    1  2  ?  6   1
4  38   0   4  105   0  ?  0  166  0  2.8  1  ?  ?   2

In [57]:
swiss_data.describe(include='all')
# use include='all' to describe all the columns
# NaN means Not A Value
# NaN + anything(integer, float like 8 or 5.0) = NaN

                0           1           2    3      4    5    6    7    8    9    10   11   12          13
count   123.000000  123.000000  123.000000  123  123.0  123  123  123  123  123  123  123  123  123.000000
unique         NaN         NaN         NaN   21    NaN    3    4   68    3   36    4    3    4         NaN
top            NaN         NaN         NaN  115    NaN    ?    0  120    0    0    2    ?    ?         NaN
freq           NaN         NaN         NaN   14    NaN   75   85    9   68   42   61  118   52         NaN
mean     55.317073    0.918699    3.699187  NaN    0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    1.804878
std       9.032108    0.274414    0.688726  NaN    0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    1.013503
min      32.000000    0.000000    1.000000  NaN    0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    0.000000
25%      51.000000    1.000000    4.000000  NaN    0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    1.000000
50%      56.000000    1.000000    4.000000  NaN    0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    2.000000
75%      61.500000    1.000000    4.000000  NaN    0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    3.000000
max      74.000000    1.000000    4.000000  NaN    0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    4.000000

In [ ]:
swiss_data = swiss_data.replace('?', pd.NA) # replacing the ? with 0s
# since the 3rd index column is actually a string, that's why the values are NaN.
# due to jupyter notebook's internal memory, sometimes previous states, given to replace are logged permanently.
# reruning all the cells once again would wave it off.

In [59]:
swiss_data.head()

   0   1   2    3   4    5    6    7  8    9    10   11   12  13
0  32   1   1   95   0  NaN    0  127  0   .7    1  NaN  NaN   1
1  34   1   4  115   0  NaN  NaN  154  0   .2    1  NaN  NaN   1
2  35   1   4  NaN   0  NaN    0  130  1  NaN  NaN  NaN    7   3
3  36   1   4  110   0  NaN    0  125  1    1    2  NaN    6   1
4  38   0   4  105   0  NaN    0  166  0  2.8    1  NaN  NaN   2