# Data Preparation - Heart Disease Detection
---
## This Notebook is to prepare the final Data, which will be directly used in the Model Training

In [109]:
# importing necessary modules
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer

### Loading the data

In [110]:
cleve_data = pd.read_csv('data/processed.cleveland.data', header=None)
swiss_data = pd.read_csv('data/processed.switzerland.data', header=None)
va_data = pd.read_csv('data/processed.va.data', header=None)
hungarian_data = pd.read_csv('data/processed.hungarian.data', header=None)

### Stacking / Merging the Data

In [111]:
merged_data = pd.concat([cleve_data, swiss_data, va_data, hungarian_data], axis=0)

In [112]:
merged_data.info()

<class 'pandas.DataFrame'>
Index: 920 entries, 0 to 293
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       920 non-null    float64
 1   1       920 non-null    float64
 2   2       920 non-null    float64
 3   3       920 non-null    object
 4   4       920 non-null    object
 5   5       920 non-null    object
 6   6       920 non-null    object
 7   7       920 non-null    object
 8   8       920 non-null    object
 9   9       920 non-null    object
 10  10      920 non-null    object
 11  11      920 non-null    str
 12  12      920 non-null    str
 13  13      920 non-null    int64
dtypes: float64(3), int64(1), object(8), str(2)
memory usage: 107.8+ KB

In [113]:
merged_data = merged_data.replace('?', pd.NA) # replacing ? with NaN

In [114]:
merged_data.info()

<class 'pandas.DataFrame'>
Index: 920 entries, 0 to 293
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       920 non-null    float64
 1   1       920 non-null    float64
 2   2       920 non-null    float64
 3   3       861 non-null    object
 4   4       890 non-null    object
 5   5       830 non-null    object
 6   6       918 non-null    object
 7   7       865 non-null    object
 8   8       865 non-null    object
 9   9       858 non-null    object
 10  10      611 non-null    object
 11  11      309 non-null    str
 12  12      434 non-null    str
 13  13      920 non-null    int64
dtypes: float64(3), int64(1), object(8), str(2)
memory usage: 107.8+ KB

In [115]:

merged_data = merged_data.astype('Float64')

In [116]:
merged_data.info()

<class 'pandas.DataFrame'>
Index: 920 entries, 0 to 293
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       920 non-null    Float64
 1   1       920 non-null    Float64
 2   2       920 non-null    Float64
 3   3       861 non-null    Float64
 4   4       890 non-null    Float64
 5   5       830 non-null    Float64
 6   6       918 non-null    Float64
 7   7       865 non-null    Float64
 8   8       865 non-null    Float64
 9   9       858 non-null    Float64
 10  10      611 non-null    Float64
 11  11      309 non-null    Float64
 12  12      434 non-null    Float64
 13  13      920 non-null    Float64
dtypes: Float64(14)
memory usage: 120.4 KB

## Splitting the Data

In [117]:
# Splitting the data
merged_input = merged_data.iloc[: , [x for x in range(13)]].copy()

In [118]:
merged_input.head()

     0    1    2      3      4    5    6      7    8    9    10   11   12
0  63.0  1.0  1.0  145.0  233.0  1.0  2.0  150.0  0.0  2.3  3.0  0.0  6.0
1  67.0  1.0  4.0  160.0  286.0  0.0  2.0  108.0  1.0  1.5  2.0  3.0  3.0
2  67.0  1.0  4.0  120.0  229.0  0.0  2.0  129.0  1.0  2.6  2.0  2.0  7.0
3  37.0  1.0  3.0  130.0  250.0  0.0  0.0  187.0  0.0  3.5  3.0  0.0  3.0
4  41.0  0.0  2.0  130.0  204.0  0.0  2.0  172.0  0.0  1.4  1.0  0.0  3.0

In [119]:
merged_data.head()

     0    1    2      3      4    5    6      7    8    9    10   11   12   13
0  63.0  1.0  1.0  145.0  233.0  1.0  2.0  150.0  0.0  2.3  3.0  0.0  6.0  0.0
1  67.0  1.0  4.0  160.0  286.0  0.0  2.0  108.0  1.0  1.5  2.0  3.0  3.0  2.0
2  67.0  1.0  4.0  120.0  229.0  0.0  2.0  129.0  1.0  2.6  2.0  2.0  7.0  1.0
3  37.0  1.0  3.0  130.0  250.0  0.0  0.0  187.0  0.0  3.5  3.0  0.0  3.0  0.0
4  41.0  0.0  2.0  130.0  204.0  0.0  2.0  172.0  0.0  1.4  1.0  0.0  3.0  0.0

In [120]:
merged_output = merged_data.iloc[:, [13]].copy()

In [121]:
merged_output.head()

    13
0  0.0
1  2.0
2  1.0
3  0.0
4  0.0

In [122]:
merged_output.info()

<class 'pandas.DataFrame'>
Index: 920 entries, 0 to 293
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   13      920 non-null    Float64
dtypes: Float64(1)
memory usage: 15.3 KB

### Test Train Split

In [123]:
train_x, test_x, train_y, test_y = train_test_split(merged_input, merged_output, test_size=.3, random_state=28, shuffle=True)

In [124]:
train_x.info()

<class 'pandas.DataFrame'>
Index: 644 entries, 268 to 257
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       644 non-null    Float64
 1   1       644 non-null    Float64
 2   2       644 non-null    Float64
 3   3       602 non-null    Float64
 4   4       620 non-null    Float64
 5   5       595 non-null    Float64
 6   6       642 non-null    Float64
 7   7       604 non-null    Float64
 8   8       604 non-null    Float64
 9   9       602 non-null    Float64
 10  10      423 non-null    Float64
 11  11      213 non-null    Float64
 12  12      304 non-null    Float64
dtypes: Float64(13)
memory usage: 78.6 KB

In [125]:
print(train_x.shape)
print(train_y.shape)

(644, 13)
(644, 1)

In [126]:
print(test_x.shape)
print(test_y.shape)

(276, 13)
(276, 1)

In [127]:
validation_x, test_x, validation_y, test_y = train_test_split(test_x, test_y, test_size=.5)

In [128]:
print(validation_x.shape)
print(validation_y.shape)
print(test_x.shape)
print(test_y.shape)

(138, 13)
(138, 1)
(138, 13)
(138, 1)

## Imputation

In [129]:
train_x.describe(include='all')

,0,1,2,3,4,5,6,7,8,9,10,11,12
count,644.0,644.0,644.0,602.0,620.0,595.0,642.0,604.0,604.0,602.0,423.0,213.0,304.0
mean,53.57764,0.798137,3.273292,132.405316,204.274194,0.178151,0.58567,137.402318,0.405629,0.879568,1.780142,0.690141,5.220395
std,9.195062,0.401703,0.912928,18.748582,107.306646,0.382962,0.793684,25.395617,0.49142,1.07217,0.585272,0.945569,1.886406
min,28.0,0.0,1.0,0.0,0.0,0.0,0.0,60.0,0.0,-2.0,1.0,0.0,3.0
25%,48.0,1.0,3.0,120.0,182.0,0.0,0.0,120.0,0.0,0.0,1.0,0.0,3.0
50%,54.0,1.0,4.0,130.0,226.5,0.0,0.0,140.0,0.0,0.5,2.0,0.0,6.0
75%,60.0,1.0,4.0,140.0,268.0,0.0,1.0,156.0,1.0,1.5,2.0,1.0,7.0
max,77.0,1.0,4.0,200.0,603.0,1.0,2.0,195.0,1.0,6.2,3.0,3.0,7.0

In [131]:
# Imputation
imputer = KNNImputer(n_neighbors=5)

train_x = imputer.fit_transform(train_x) # fit to prevent data leakage

test_x = imputer.transform(test_x)
validation_x = imputer.transform(validation_x)

In [133]:
# Converting data back to dataframe
train_x = pd.DataFrame(train_x, columns=None)
test_x = pd.DataFrame(test_x, columns=None)
validation_x = pd.DataFrame(validation_x, columns=None)

In [138]:
train_x.head()

     0    1    2      3      4    5    6      7    8    9    10   11   12
0  40.0  1.0  4.0  152.0  223.0  0.0  0.0  181.0  0.0  0.0  1.0  0.0  7.0
1  39.0  0.0  3.0  110.0  182.0  0.0  1.0  180.0  0.0  0.0  1.2  0.2  4.4
2  62.0  0.0  4.0  160.0  164.0  0.0  2.0  145.0  0.0  6.2  3.0  3.0  7.0
3  55.0  1.0  4.0  158.0  217.0  0.0  0.0  110.0  1.0  2.5  2.0  0.8  6.2
4  47.0  1.0  3.0  155.0    0.0  0.0  0.0  118.0  1.0  1.0  2.0  0.6  3.0

## Preparing Final Data

In [139]:
train_x.info()

<class 'pandas.DataFrame'>
RangeIndex: 644 entries, 0 to 643
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       644 non-null    float64
 1   1       644 non-null    float64
 2   2       644 non-null    float64
 3   3       644 non-null    float64
 4   4       644 non-null    float64
 5   5       644 non-null    float64
 6   6       644 non-null    float64
 7   7       644 non-null    float64
 8   8       644 non-null    float64
 9   9       644 non-null    float64
 10  10      644 non-null    float64
 11  11      644 non-null    float64
 12  12      644 non-null    float64
dtypes: float64(13)
memory usage: 65.5 KB

In [144]:
# Stacking / Concatenating the Values
final_train_data = pd.concat([train_x, train_y], axis=0)

In [145]:
final_train_data.shape

(1288, 14)

In [146]:
final_train_data.info()

<class 'pandas.DataFrame'>
Index: 1288 entries, 0 to 257
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       644 non-null    float64
 1   1       644 non-null    float64
 2   2       644 non-null    float64
 3   3       644 non-null    float64
 4   4       644 non-null    float64
 5   5       644 non-null    float64
 6   6       644 non-null    float64
 7   7       644 non-null    float64
 8   8       644 non-null    float64
 9   9       644 non-null    float64
 10  10      644 non-null    float64
 11  11      644 non-null    float64
 12  12      644 non-null    float64
 13  13      644 non-null    Float64
dtypes: Float64(1), float64(13)
memory usage: 152.2 KB

In [147]:
final_validation_data = pd.concat([validation_x, validation_y], axis=0)
final_test_data = pd.concat([test_x, test_y], axis=0)

## Exporting the Data

In [150]:
# Exporting the data 
final_train_data.to_csv('data/FinalDataSets/train.csv')
final_validation_data.to_csv('data/FinalDataSets/validation.csv')
final_test_data.to_csv('data/FinalDataSets/test.csv')